
name: Build Debug APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesar pentru a crea release-uri

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create debug.keystore
      run: |
        keytool -genkey -v -keystore app/debug.keystore \
          -storepass android -alias androiddebugkey -keypass android \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "C=US, O=Android, CN=Android Debug"

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Define Release and APK names
      id: set_names
      run: |
        echo "release_title=Water Reminder v2.0.${{ github.run_number }}" >> $GITHUB_OUTPUT
        echo "apk_name=Water-Reminder-v2.0.${{ github.run_number }}.apk" >> $GITHUB_OUTPUT

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk ${{ steps.set_names.outputs.apk_name }}

    - name: Upload APK as Release Artifact
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ steps.set_names.outputs.apk_name }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v2.0.${{ github.run_number }}"
        name: "${{ steps.set_names.outputs.release_title }}"
        body: "APK pentru instalare. Creat de pe urma acestui [commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})."
        allowUpdates: true
